/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ADMIN_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AUTH_API_URL": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "AWS_SES_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SES_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": import("@cloudflare/workers-types").Service
    "AuthApi": import("@cloudflare/workers-types").Service
    "AuthStorage": import("@cloudflare/workers-types").KVNamespace
    "Bucket": import("@cloudflare/workers-types").R2Bucket
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_DEFAULT_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Console": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "DISCORD_SUPPORT_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_SUPPORT_CHANNEL_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "EnterpriseStorage": import("@cloudflare/workers-types").R2Bucket
    "FEISHU_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FEISHU_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QuotaService": import("@cloudflare/workers-types").Service
    "QuotaServiceToken": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "R2AccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2SecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPPORT_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Stat": import("@cloudflare/workers-types").Service
    "Stats": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "Teams": {
      "type": "sst.cloudflare.SolidStart"
      "url": string
    }
    "UsageQueue": import("@cloudflare/workers-types").Queue
    "Web": {
      "type": "sst.cloudflare.Astro"
      "url": string
    }
    "WebApp": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "ZEN_BLACK_PRICE": {
      "plan100": string
      "plan20": string
      "plan200": string
      "product": string
      "type": "sst.sst.Linkable"
    }
    "ZEN_LIMITS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_LITE_PRICE": {
      "firstMonth100Coupon": string
      "firstMonth50Coupon": string
      "price": string
      "priceInr": number
      "product": string
      "sixMonths100Coupon": string
      "threeMonths100Coupon": string
      "twelveMonths100Coupon": string
      "type": "sst.sst.Linkable"
    }
    "ZenData": import("@cloudflare/workers-types").R2Bucket
    "ZenDataNew": import("@cloudflare/workers-types").R2Bucket
  }
}

import "sst"
export {}
