import { describe, expect, test } from "bun:test"
import { getTableColumns, getTableName } from "drizzle-orm"
import type { Table } from "drizzle-orm"
import * as d1 from "../src/schema-d1"

const contract = {
  AccountTable: [
    "id",
    "status",
    "auth_version",
    "suspension_reason",
    "suspended_by",
    "time_suspended",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  AccountDeletionTable: [
    "id",
    "account_id",
    "status",
    "attempts",
    "last_error_code",
    "time_eligible",
    "time_started",
    "time_completed",
    "time_cancelled",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  AuthTable: ["id", "timeCreated", "timeUpdated", "timeDeleted", "provider", "subject", "accountID"],
  PlatformAdminTable: [
    "id",
    "email",
    "access_subject",
    "role",
    "status",
    "time_last_seen",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  AdminAuditLogTable: [
    "id",
    "admin_id",
    "actor_email",
    "action",
    "target_type",
    "target_id",
    "outcome",
    "request_id",
    "source_ip",
    "user_agent",
    "metadata",
    "time_created",
  ],
  BenchmarkTable: ["id", "timeCreated", "timeUpdated", "timeDeleted", "model", "agent", "result"],
  NewsletterSubscriberTable: [
    "email",
    "locale",
    "source",
    "status",
    "consentVersion",
    "timeConsented",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "timeUnsubscribed",
  ],
  EnterpriseInquiryTable: [
    "id",
    "name",
    "role",
    "company",
    "email",
    "phone",
    "message",
    "locale",
    "source",
    "status",
    "formVersion",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  BillingTable: [
    "id",
    "workspaceID",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "customerID",
    "paymentMethodID",
    "paymentMethodType",
    "paymentMethodLast4",
    "balance",
    "monthlyLimit",
    "monthlyUsage",
    "timeMonthlyUsageUpdated",
    "reload",
    "reloadTrigger",
    "reloadAmount",
    "reloadError",
    "timeReloadError",
    "timeReloadLockedTill",
    "subscription",
    "subscriptionID",
    "subscriptionPlan",
    "timeSubscriptionBooked",
    "timeSubscriptionSelected",
    "liteSubscriptionID",
    "lite",
  ],
  SubscriptionTable: [
    "id",
    "workspaceID",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "userID",
    "rollingUsage",
    "fixedUsage",
    "weeklyTokens",
    "timeRollingUpdated",
    "timeFixedUpdated",
    "timeWeeklyTokensUpdated",
  ],
  PlanSubscriptionTable: [
    "id",
    "workspaceID",
    "invoiceID",
    "plan",
    "status",
    "timePeriodStart",
    "timePeriodEnd",
    "timeCancelled",
    "timeRefunded",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  LiteTable: [
    "id",
    "workspaceID",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "userID",
    "rollingUsage",
    "weeklyUsage",
    "monthlyUsage",
    "timeRollingUpdated",
    "timeWeeklyUpdated",
    "timeMonthlyUpdated",
  ],
  PaymentTable: [
    "id",
    "workspaceID",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "customerID",
    "invoiceID",
    "paymentID",
    "amount",
    "timeRefunded",
    "enrichment",
  ],
  PaymentInvoiceTable: [
    "id",
    "workspace_id",
    "provider",
    "merchant_account_id",
    "external_invoice_id",
    "external_payment_id",
    "purpose",
    "plan",
    "amount",
    "currency",
    "status",
    "time_expires",
    "time_failed",
    "time_expired",
    "time_cancelled",
    "time_verified",
    "time_refunded",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  PaymentCheckoutTable: [
    "id",
    "workspace_id",
    "account_id",
    "request_key",
    "provider",
    "merchant_account_id",
    "external_invoice_id",
    "purpose",
    "plan",
    "amount",
    "currency",
    "checkout",
    "creation_error_code",
    "status",
    "time_expires",
    "time_ready",
    "time_failed",
    "time_expired",
    "time_cancelled",
    "time_paid",
    "time_refunded",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  PaymentCancellationTable: [
    "invoice_id",
    "workspace_id",
    "account_id",
    "request_key",
    "provider",
    "merchant_account_id",
    "external_invoice_id",
    "status",
    "error_code",
    "time_requested",
    "time_completed",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  PaymentEventTable: [
    "id",
    "invoice_id",
    "workspace_id",
    "provider",
    "merchant_account_id",
    "external_event_id",
    "external_invoice_id",
    "external_payment_id",
    "amount",
    "currency",
    "type",
    "outcome",
    "from_status",
    "to_status",
    "payload_hash",
    "time_occurred",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
  ],
  UsageTable: [
    "id",
    "workspaceID",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "model",
    "provider",
    "inputTokens",
    "outputTokens",
    "reasoningTokens",
    "cacheReadTokens",
    "cacheWrite5mTokens",
    "cacheWrite1hTokens",
    "cost",
    "inputCost",
    "outputCost",
    "cacheReadCost",
    "cacheWriteCost",
    "country",
    "continent",
    "keyID",
    "sessionID",
    "enrichment",
  ],
  FinanceFxRateTable: [
    "id",
    "base_currency",
    "quote_currency",
    "rate_micromnt_per_usd",
    "source",
    "source_reference",
    "idempotency_key",
    "payload_hash",
    "time_effective",
    "time_created",
  ],
  FinanceCostEntryTable: [
    "id",
    "workspace_id",
    "category",
    "direction",
    "basis",
    "source_type",
    "source_reference",
    "usage_id",
    "payment_invoice_id",
    "payment_event_id",
    "provider",
    "model",
    "original_amount",
    "original_currency",
    "fx_rate_id",
    "amount_mnt_micros",
    "idempotency_key",
    "payload_hash",
    "time_effective",
    "time_created",
  ],
  FinanceCostValuationTable: [
    "id",
    "cost_entry_id",
    "fx_rate_id",
    "method",
    "version",
    "amount_mnt_micros",
    "idempotency_key",
    "payload_hash",
    "time_created",
  ],
  FinancePaymentSettlementTable: [
    "id",
    "workspace_id",
    "payment_invoice_id",
    "payment_event_id",
    "provider",
    "merchant_account_id",
    "external_settlement_id",
    "kind",
    "gross_amount_mnt",
    "fee_amount_mnt",
    "tax_amount_mnt",
    "net_amount_mnt",
    "currency",
    "idempotency_key",
    "payload_hash",
    "time_effective",
    "time_created",
  ],
  CouponTable: ["email", "type", "timeRedeemed"],
  IpTable: ["ip", "timeCreated", "timeUpdated", "timeDeleted", "usage"],
  IpRateLimitTable: ["ip", "interval", "count"],
  KeyRateLimitTable: ["key", "interval", "count"],
  ModelTpmRateLimitTable: ["id", "interval", "count"],
  ModelTpsRateLimitTable: ["id", "interval", "qualify", "unqualify"],
  ModelStickyProviderTable: ["id", "timeCreated", "timeUpdated", "timeDeleted", "providerId"],
  KeyTable: ["id", "workspaceID", "timeCreated", "timeUpdated", "timeDeleted", "name", "key", "userID", "timeUsed"],
  ModelTable: ["id", "workspaceID", "timeCreated", "timeUpdated", "timeDeleted", "model"],
  ProviderTable: ["id", "workspaceID", "timeCreated", "timeUpdated", "timeDeleted", "provider", "credentials"],
  ReferralCodeTable: ["workspaceID", "code", "timeCreated", "timeUpdated", "timeDeleted"],
  ReferralTable: ["id", "workspaceID", "timeCreated", "timeUpdated", "timeDeleted", "inviteeAccountID"],
  ReferralRewardTable: [
    "workspaceID",
    "referralID",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "amount",
    "timeApplied",
  ],
  UserTable: [
    "id",
    "workspaceID",
    "timeCreated",
    "timeUpdated",
    "timeDeleted",
    "accountID",
    "email",
    "name",
    "timeSeen",
    "color",
    "role",
    "monthlyLimit",
    "monthlyUsage",
    "timeMonthlyUsageUpdated",
  ],
  WorkspaceTable: ["id", "slug", "name", "timeCreated", "timeUpdated", "timeDeleted"],
} as const

describe("D1 schema contract", () => {
  for (const [exportName, columns] of Object.entries(contract)) {
    test(`${exportName} keeps its table and column contract`, () => {
      // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion -- Object.entries cannot preserve literal keys
      const table = d1[exportName as keyof typeof contract] as Table
      expect(getTableName(table)).toBe(
        exportName
          .replace(/Table$/, "")
          .replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
          .replace(/^_/, ""),
      )
      expect(Object.keys(getTableColumns(table))).toEqual([...columns])
    })
  }

  test("keeps product enums aligned", () => {
    expect(d1.AccountStatuses).toEqual(["active", "suspended"])
    expect(d1.AccountDeletionStatuses).toEqual(["requested", "processing", "completed", "failed", "cancelled"])
    expect(d1.AuthProvider).toEqual(["email", "github", "google"])
    expect(d1.UserRole).toEqual(["admin", "member"])
    expect(d1.PlatformAdminRoles).toEqual(["owner", "administrator", "support", "finance", "operations"])
    expect(d1.PlatformAdminStatuses).toEqual(["active", "suspended"])
    expect(d1.AdminAuditOutcomes).toEqual(["success", "denied", "failure"])
    expect(d1.PlanNames).toEqual(["basic", "pro", "max"])
    expect(d1.PaymentProviders).toEqual(["qpay", "bonum"])
    expect(d1.PaymentPurposes).toEqual(["subscription", "credit"])
    expect(d1.FinanceCurrencies).toEqual(["MNT", "USD"])
    expect(d1.FinanceCostCategories).toEqual(["model_cost", "payment_fee", "tax", "adjustment"])
    expect(d1.FinanceCostDirections).toEqual(["debit", "credit"])
    expect(d1.FinanceCostBases).toEqual(["estimated", "actual", "allocated"])
    expect(d1.FinanceCostSourceTypes).toEqual(["usage", "provider_statement", "payment_settlement", "manual"])
    expect(d1.FinanceCostValuationMethods).toEqual(["historical_spot", "provider_settlement", "manual"])
    expect(d1.FinancePaymentSettlementKinds).toEqual(["payment", "refund", "adjustment"])
    expect(d1.PaymentInvoiceStatuses).toEqual([
      "created",
      "pending",
      "paid",
      "failed",
      "expired",
      "cancelled",
      "refunded",
    ])
    expect(d1.PaymentCheckoutStatuses).toEqual([
      "creating",
      "unknown",
      "ready",
      "pending",
      "paid",
      "failed",
      "expired",
      "cancelled",
      "refunded",
    ])
    expect(d1.PaymentCancellationStatuses).toEqual(["requested", "unknown", "cancelled", "failed"])
    expect(d1.PaymentEventTypes).toEqual(["pending", "paid", "failed", "expired", "cancelled", "refunded"])
    expect(d1.PaymentEventOutcomes).toEqual(["applied", "noop", "rejected"])
    expect(d1.PlanSubscriptionStatuses).toEqual(["active", "expired", "cancelled", "refunded"])
    expect(d1.NewsletterSubscriberStatus).toEqual(["active", "unsubscribed"])
    expect(d1.NewsletterSubscriberSource).toEqual(["console", "stats"])
    expect(d1.EnterpriseInquiryStatus).toEqual(["new", "reviewing", "resolved", "spam"])
    expect(d1.EnterpriseInquirySource).toEqual(["enterprise"])
  })
})
