export const requiredDocsTopics = [
  "account",
  "admin",
  "billing",
  "cli",
  "deployment",
  "desktop",
  "ecosystem",
  "faq",
  "install",
  "incident-response",
  "mcp-servers",
  "models",
  "plugins",
  "privacy",
  "providers",
  "release-upgrade",
  "security",
  "skills",
  "troubleshooting",
  "web",
] as const

export const requiredDocsSearchResults = [
  ["Free Auto", "/docs/account/"],
  ["алдаа оношлох", "/docs/troubleshooting/"],
  ["MCP серверүүд", "/docs/mcp-servers/"],
  ["Аюулгүй ашиглалт", "/docs/security/"],
  ["Буцаах төлөвлөгөө", "/docs/release-upgrade/"],
  ["Ослын хариу арга хэмжээ", "/docs/incident-response/"],
  ["Claude Codex Goose", "/docs/ecosystem/"],
  ["NVIDIA NIM", "/docs/providers/"],
  ["Ollama LM Studio", "/docs/providers/"],
  ["залгаас", "/docs/plugins/"],
  ["SKILL.md", "/docs/skills/"],
  ["QPay Bonum", "/docs/billing/"],
  ["Нууцлал өгөгдлийн амьдралын мөчлөг", "/docs/privacy/"],
  ["RBAC MFA", "/docs/admin/"],
] as const
