name: Шинэ боломж санал болгох
description: Шинэ санаа, боломж эсвэл сайжруулалтын санал илгээнэ үү
title: "[САНАЛ]:"

body:
  - type: checkboxes
    id: verified
    attributes:
      label: Энэ саналыг өмнө нь илгээгээгүйг шалгана уу
      options:
        - label: Ижил санал өмнө нь бүртгэгдээгүйг issue хайлтаар шалгасан.
          required: true

  - type: textarea
    attributes:
      label: Хүсэж буй сайжруулалтаа тайлбарлана уу
      description: Юуг өөрчлөх эсвэл нэмэх, хэрэглэгчид ямар ашигтайг ойлгомжтой тайлбарлана уу
    validations:
      required: true
