import { describe, expect, test } from "bun:test"

const mongolgpt = new URL("../../mongolgpt/src/", import.meta.url)
const tui = new URL("../../tui/src/", import.meta.url)
const sessionUi = new URL("../../session-ui/src/", import.meta.url)

describe("Монгол хэрэглэгчийн интерфэйсийн гэрээ", () => {
  test("CLI-ийн шинэчлэх, устгах болон MCP урсгалыг Монгол хэлээр үзүүлнэ", async () => {
    const upgrade = await Bun.file(new URL("cli/cmd/upgrade.ts", mongolgpt)).text()
    const uninstall = await Bun.file(new URL("cli/cmd/uninstall.ts", mongolgpt)).text()
    const mcp = await Bun.file(new URL("cli/cmd/mcp.ts", mongolgpt)).text()
    const providers = await Bun.file(new URL("cli/cmd/providers.ts", mongolgpt)).text()
    const errors = await Bun.file(new URL("cli/error.ts", mongolgpt)).text()
    const compatibility = await Bun.file(new URL("cli/cmd/compat.ts", mongolgpt)).text()
    const web = await Bun.file(new URL("cli/cmd/web.ts", mongolgpt)).text()

    expect(upgrade).toContain('prompts.intro("MongolGPT шинэчлэх")')
    expect(upgrade).toContain('spinner.start("Шинэчилж байна...")')
    expect(upgrade).not.toContain('prompts.intro("Upgrade")')
    expect(upgrade).not.toContain("package manager-аар")

    expect(uninstall).toContain('message: "MongolGPT-ийг устгахдаа итгэлтэй байна уу?"')
    expect(uninstall).toContain('label: "Кэш"')
    expect(uninstall).toContain('keepOption: "--keep-data"')
    expect(uninstall).toContain('keepOption: "--keep-config"')
    expect(uninstall).not.toContain('label: "Cache"')
    expect(uninstall).not.toContain("--keep-${dir.label.toLowerCase()}")

    expect(mcp).toContain('placeholder: "жишээ нь mongolgpt x @modelcontextprotocol/server-filesystem"')
    expect(mcp).toContain('placeholder: "жишээ нь https://example.com/mcp"')
    expect(mcp).not.toContain('placeholder: "e.g.,')
    expect(mcp).toContain('message: "OAuth клиентийн ID оруулна уу"')
    expect(mcp).toContain('message: "OAuth клиентийн нууцыг оруулна уу"')
    expect(mcp).not.toContain('message: "Client ID оруулна уу"')
    expect(mcp).not.toContain('message: "Client secret оруулна уу"')
    expect(mcp).toContain('spinner.stop("Хөтөч дээрээ зөвшөөрөл олгоно уу:")')
    expect(mcp).not.toContain('spinner.stop("Browser дээрээ зөвшөөрөл олгоно уу:")')

    expect(providers).toContain('message: "API түлхүүрээ оруулна уу"')
    expect(providers).toContain('message: "Үйлчилгээ үзүүлэгч сонгоно уу"')
    expect(providers).toContain('message: "Үйлчилгээ үзүүлэгчийн ID оруулна уу"')
    expect(providers).not.toContain('message: "API key-ээ оруулна уу"')
    expect(providers).not.toContain('message: "Provider сонгоно уу"')

    expect(errors).toContain("Алсын тохиргоо")
    expect(errors).toContain("нэвтрэх хуудас буцаалаа")
    expect(errors).toContain("Нэвтрэх баталгаажуулалт")
    expect(errors).not.toContain("Remote config")
    expect(errors).not.toContain("login page буцаалаа")
    expect(errors).not.toContain("Authentication алга")
    expect(errors).not.toContain("түгээмэл typo")
    expect(compatibility).toContain('prompts.outro("Туршилтын горим дууслаа. Файл өөрчлөгдөөгүй.")')
    expect(compatibility).not.toContain('prompts.outro("Dry run дууслаа. Файл өөрчлөгдөөгүй.")')
    expect(web).toContain('describe: "MongolGPT сервер эхлүүлж вэб интерфэйс нээх"')
    expect(web).not.toContain('describe: "MongolGPT сервер эхлүүлж web интерфэйс нээх"')
  })

  test("CLI footer болон TUI-ийн командын тайлбар Монгол байна", async () => {
    const footer = await Bun.file(new URL("cli/cmd/run/footer.view.tsx", mongolgpt)).text()
    const dialog = await Bun.file(new URL("ui/dialog-select.tsx", tui)).text()
    const whichKey = await Bun.file(new URL("feature-plugins/system/which-key.tsx", tui)).text()
    const workspace = await Bun.file(new URL("component/dialog-workspace-create.tsx", tui)).text()
    const prompt = await Bun.file(new URL("component/prompt/index.tsx", tui)).text()
    const mcpSidebar = await Bun.file(new URL("feature-plugins/sidebar/mcp.tsx", tui)).text()
    const question = await Bun.file(new URL("routes/session/question.tsx", tui)).text()
    const providerDialog = await Bun.file(new URL("component/dialog-provider.tsx", tui)).text()
    const toolDisplay = await Bun.file(new URL("util/tool-display.ts", tui)).text()
    const local = await Bun.file(new URL("context/local.tsx", tui)).text()
    const editor = await Bun.file(new URL("editor.ts", tui)).text()
    const errors = await Bun.file(new URL("util/error.ts", tui)).text()
    const clipboard = await Bun.file(new URL("clipboard.ts", tui)).text()
    const messagePart = await Bun.file(new URL("components/message-part.tsx", sessionUi)).text()

    expect(footer).toContain('label: "арын горим"')
    expect(footer).toContain("label: `${queue()} дараалалд`")
    expect(footer).toContain('label: "дэд агент"')
    expect(footer).toContain('label: "энгийн горим"')
    expect(footer).toContain('label: "команд"')
    expect(footer).toContain('category: "Хүсэлт"')
    expect(footer).toContain('category: "Загвар"')
    expect(footer).toContain('category: "Сешн"')
    expect(footer).not.toContain('category: "Model"')
    expect(footer).not.toContain('category: "Session"')

    expect(dialog).toContain('category: "Цонх"')
    expect(dialog).not.toContain('category: "Dialog"')
    expect(whichKey).toContain('desc: "Товчны туслахыг асаах/унтраах"')
    expect(workspace).toContain('title: "Ажлын орчны холбогчдыг ачаалж чадсангүй"')
    expect(prompt).toContain("терминалын горимоос гарах")
    expect(mcpSidebar).toContain("Клиентийн ID шаардлагатай")
    expect(question).toContain('group: "Асуулт"')
    expect(question).not.toContain('group: "Question"')
    expect(providerDialog).toContain('openai: "(ChatGPT Plus/Pro эсвэл API түлхүүр)"')
    expect(providerDialog).not.toContain('openai: "(ChatGPT Plus/Pro or API key)"')
    expect(toolDisplay).toContain('return "Parallel үйлчилгээгээр вэб хайх"')
    expect(toolDisplay).toContain('return "Exa үйлчилгээгээр вэб хайх"')
    expect(messagePart).toContain('i18n.t("ui.tool.websearch.parallel")')
    expect(messagePart).toContain('i18n.t("ui.tool.websearch.exa")')
    expect(messagePart).not.toContain('return "Parallel Web Search"')
    expect(messagePart).not.toContain('return "Exa Web Search"')
    expect(messagePart).toContain('cleaned.includes("энэ асуултаас татгалзлаа")')
    expect(local).toContain('message: "Энэ товчлолыг ашиглахын тулд дуртай загвар нэмнэ үү"')
    expect(local).not.toContain("shortcut-ыг")
    expect(local).not.toContain("favorite model")
    expect(editor).toContain("гаралтын кодоор")
    expect(editor).toContain("дохиогоор")
    expect(editor).not.toContain("signal` : `${code} code")
    expect(errors).not.toContain("түгээмэл typo")
    expect(clipboard).toContain("гаралтын кодоор дууслаа")
    expect(clipboard).not.toContain("code-той дууслаа")
  })
})
