name: release-github-action

on:
  push:
    branches:
      - dev
    paths:
      - "github/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Release
        run: |
          git config --global user.email "mongolgpt@sst.dev"
          git config --global user.name "mongolgpt"
          ./github/script/release
